### ISSUE TITLE
2023-13-08: Tweets not embedding

### ISSUE THREAD

**Issue by dylanpdx** [dylanpdx/BetterTwitFix#130]
Investigating this issue where Tweets are not embedding properly.

So far, I have found that Twitter is returning an empty response when I ask for info about a Tweet

**Comment by dylanpdx** [comment]
A fix has been deployed, currently looking to see if this stabilizes things. It might take up to 30 minutes for Discord to update their cache

**Comment by neirusalwa** [comment]
seems functional here

**Comment by neirusalwa** [comment]
update : seems inconsistent. some links work fine but some dont

**Comment by dylanpdx** [comment]
Made some other changes behind the scenes which should improve things, I hope

**Comment by neirusalwa** [comment]
seems resolved but the tweet that was broken before seems broken still (maybe caching issue?) 
problematic one : https://vxtwitter.com/eatery1234/status/1690615633757802496?s=20

**Comment by dylanpdx** [comment]
Probably a caching issue. I reset the cache on my end of things so hopefully it all starts working again

**Comment by neirusalwa** [comment]
yup seems resolved. was most likely expired cache 👍 thanks

**Comment by dylanpdx** [comment]
Issue resolved I guess!

**Comment by neirusalwa** [comment]
seems like the combined image tweets cant be maximized properly (4 images in 1 tweet for example) ![Screenshot_20230814_010751.jpg](https://github.com/dylanpdx/BetterTwitFix/assets/14804553/5012e4dc-5719-4f14-a868-c043c0ac3bf1)

the screenshot ive provided is what happens when i click on such embed image on android. could test on my iphone but i dont have access to it right now

**Comment by dylanpdx** [comment]
This error usually happens if the tweet has been deleted

**Comment by neirusalwa** [comment]
gotcha, ty👍
