### ISSUE TITLE
Text and account links are seemingly swapped

### ISSUE THREAD

**Issue by dabluecaboose** [dylanpdx/BetterTwitFix#83]
When clicking a vxtwitter embed, the link for the tweet text goes to the account user's page.

When clicking the name of the user, it goes to the specific tweet.

This is kinda backwards from what one would expect it to be, and I think it might be a bug?

**Comment by dylanpdx** [comment]
Unfortunately it's not possible as far as I know to change where the "user" link goes (the one in blue)
![image](https://user-images.githubusercontent.com/1337360/236337392-27e9e39f-e954-4c7d-864d-0993a4ed882a.png)
The only ones I can change are the ones I have highlighted here. 
I suppose it could work if I swapped around the text but I think there's limitations on the length of text that can go on certain fields, not to mention it'd be pretty weird having the tweet text being a link. Still, I'll take a look when I have time and see what I can do

**Comment by dabluecaboose** [comment]
I'm not sure I follow.

Currently, the tweet text *is* a link.

![image](https://user-images.githubusercontent.com/25807182/236339489-7d67923e-8a57-4e33-bf25-7fa716aa9e6a.png)

This is the issue I'm referring to.  If you click the text of the tweet, it brings you to the user, but not the tweet that text is from.  If you click the user, it brings you to the tweet.

**Comment by dylanpdx** [comment]
Yes, and I cannot change the destination of "Link to Tweet" in your image, it's decided by whatever is embedding the data, in this case, Discord. I can only change the "Link to user". It's either both links redirect to the tweet itself, or the blue link redirecting to the tweet (because Discord controls that) and the tweet text linking to the user. I can't flip them around as far as I'm aware.
